function [newcell] = sort_tsp(newcell)

% order the vertices according to the optimal route generated by
% Travelling salesman problem
xyz = newcell;
userConfig = struct('xy',xyz);
resultStruct = tsp_ga(userConfig);
order = resultStruct.optRoute;
newcell = newcell(order,:);

% % order the vertices according to the angle in polar coordinate
% angle = atan((newcell(:,2)-centroid(2))./(newcell(:,1)-centroid(1))).*(newcell(:,1)>=centroid(1))+...
%     (pi+atan((newcell(:,2)-centroid(2))./(newcell(:,1)-centroid(1)))).*(newcell(:,1)<centroid(1));
% angle(angle<0) = angle(angle<0) + 2*pi;
% [val,ind] = sort(angle,'ascend');  
% newcell = newcell(ind,:);